Repository emberjs/ember-test-waiters, pull requests merged in 2020-02, with the labels that each got.

#111 Fixes default tokens to be truthy
  addon/test-waiter.ts
  tests/unit/test-waiter-test.ts
Labels: bug

#117 Rename interfaces, remove class exports.
  addon/build-waiter.ts
  addon/index.ts
  addon/noop-test-waiter.ts
  addon/test-waiter.ts
  addon/token.ts
  addon/types/index.ts
  addon/wait-for-promise.ts
  addon/waiter-manager.ts
  tests/unit/build-waiter-test.ts
  tests/unit/waiter-manager-noop-test.ts
  tests/unit/waiter-manager-test.ts
  yarn.lock
Labels: breaking

#95 Dropping support for node 8
  .github/workflows/ci-build.yml
  package.json
Labels: breaking

#122 Update dependencies / devDependencies to latest.
  addon/index.ts
  addon/wait-for-promise.ts
  package.json
  tests/unit/wait-for-promise-test.ts
  tsconfig.json
  types/global.d.ts
  yarn.lock
Labels: breaking, internal
